Refactor so we can show which VM causes an error
Example:

    Traceback (most recent call last):
      File "/usr/local/bin/proxtop", line 486, in <module>
        main()
      File "/usr/local/bin/proxtop", line 477, in __call__
        vms, crap = d.fetch()
      File "/usr/local/bin/proxtop", line 156, in fetch
        e.args[0], vm['name'], vm['id']))
    proxmoxer.core.ResourceException: 400 Bad Request:
      {"errors":{"lock":"value 'snapshot-delete' does not have a value in the
       enumeration 'migrate, backup, snapshot, rollback'"},"data":null} (for vm
       vm01.example.com (qemu/154))